version: 2
jobs:
  test:
    docker:
            - image: python:3.6
    steps:
      - checkout
      - commands:
              - python ./test.py
      - run: echo "hello world"
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
